version: "3.8"

services:
  nginx:
    image: nginx
    container_name: nginx_pupilos
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./configurations/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./apps/drupal_9:/var/www/html:rw
    links:
      - php-app
  php-app:
    build: ./configurations/docker
    container_name: php_pupilos
    volumes:
      - ./apps/drupal_9:/var/www/html:rw
      - ./configurations/others/bash_aliases.txt:/root/.bash_aliases:rw
      - ./configurations/php/custom.ini:/user/local/etc/php/conf.d/custom.ini:ro
    privileged: true
    tty: true
    links:
      - database-app
      - memcache-app
      - elasticsearch-app
  database-app:
    image: mysql:5.7
    container_name: mysql_pupilos
    environment:
      MYSQL_DATABASE: pupilos
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./configurations/mysql/config:/config
      - ./configurations/mysql/data:/var/lib/mysql
  memcache-app:
    image: memcached
    container_name: memcached_pupilos
  elasticsearch-app:
    image: elasticsearch:7.10.1
    container_name: es_pupilos
    ports:
     - "9200:9200"
     - "9300:9300"
    environment:
      discovery.type: "single-node"
  varnish-app:
    image: varnish
    container_name: varnish_pupilos
    ports:
      - "8082:80"
    volumes:
      - ./configurations/varnish/default.vcl:/etc/varnish/default.vcl:ro
    links:
      - nginx:backend-host